### ISSUE TITLE
Any way to use on Android?

### ISSUE THREAD

**Issue by ShishirModi** [dmlls/whatsapp-emoji-linux#2]
Hi!
I just wanted to know if there was any way I could use this on Android? Maybe through root?

Because this is based on linux, the process shouldn't be very different, right?

**Comment by dmlls** [comment]
Hi @ShishirModi. The only way of replacing the system emoji on Android that I'm aware of is via a Magisk module (you can find [examples](https://github.com/Keinta15/Magisk-iOS-Emoji) on GitHub). For that, your device will indeed have to be rooted.

To be honest, I can't guarantee this font will work on Android, but if you do try let me know how that went (just out of curiosity).

**Comment by ShishirModi** [comment]
I've tried installing the font, but apparently stuff works differently on Samsung phones. I'll keep you updated in case I get it to work!
Thank you!

**Comment by RaeesD** [comment]
It works perfectly fine on my Android phone, using a custom AOSP ROM though, and you will need root.
The method was to just replace /system/fonts/NotoColorEmoji.ttf with this one (after renaming) and setting the permissions to the same as the replaced file (644).

**Comment by dmlls** [comment]
@RaeesD that's good to hear 🙂

I think it would be nice to add this to the readme for future reference. If you want, you can open a PR adding the specific steps you followed (e.g., I guess you used some `adb` commands?) in the [troubleshooting](https://github.com/dmlls/whatsapp-emoji-linux/tree/main#troubleshooting-) section.

Otherwise, you can just write a comment here and I'll add it myself, but that way you won't appear as a contributor...

A third option, if you don't have the time, I can just link to your comment.

**Comment by RaeesD** [comment]
@dmlls I wrote up a short guide. Thanks for the opportunity to contribute 👍

**Comment by dmlls** [comment]
@RaeesD Thank you for the PR!

@ShishirModi I'll close this issue for now, but feel free to reopen if you find a way to make it work on Samsung.
